#include "report_generator.hpp"
#include <iostream>
#include <fstream>
#include <sstream>
#include <cstdlib>
#include <chrono>
#include <iomanip>
#include <ctime>
#include <filesystem>
#include <algorithm>

namespace fs = std::filesystem;

ReportGenerator::ReportGenerator() {}

std::string ReportGenerator::getCurrentTimestamp() {
    auto now = std::chrono::system_clock::now();
    auto time = std::chrono::system_clock::to_time_t(now);
    
    std::stringstream ss;
    ss << std::put_time(std::localtime(&time), "%Y-%m-%d %H:%M:%S");
    return ss.str();
}

std::string ReportGenerator::generateHTMLHeader(const std::string& title) {
    std::stringstream ss;
    ss << "<!DOCTYPE html>\n"
       << "<html lang=\"en\">\n"
       << "<head>\n"
       << "    <meta charset=\"UTF-8\">\n"
       << "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
       << "    <title>" << title << "</title>\n"
       << "    <style>\n"
       << "        body { font-family: 'Courier New', monospace; background-color: #1e1e1e; color: #00ff00; margin: 20px; }\n"
       << "        .header { background-color: #333; border: 2px solid #00ff00; padding: 20px; margin-bottom: 20px; }\n"
       << "        .title { font-size: 24px; font-weight: bold; text-align: center; }\n"
       << "        .subtitle { font-size: 14px; text-align: center; color: #ffff00; }\n"
       << "        .section { background-color: #222; border: 1px solid #00ff00; padding: 15px; margin-bottom: 15px; }\n"
       << "        .section-title { font-size: 16px; font-weight: bold; color: #00ff00; margin-bottom: 10px; border-bottom: 1px solid #00ff00; }\n"
       << "        .row { display: flex; padding: 5px 0; }\n"
       << "        .label { flex: 0 0 25%; font-weight: bold; color: #00ffff; }\n"
       << "        .value { flex: 1; color: #00ff00; word-break: break-all; }\n"
       << "        .status-pass { color: #00ff00; font-weight: bold; }\n"
       << "        .status-fail { color: #ff0000; font-weight: bold; }\n"
       << "        .status-inconclusive { color: #ffff00; font-weight: bold; }\n"
       << "        table { width: 100%; border-collapse: collapse; margin: 10px 0; }\n"
       << "        th, td { border: 1px solid #00ff00; padding: 8px; text-align: left; }\n"
       << "        th { background-color: #333; color: #00ffff; font-weight: bold; }\n"
       << "        .footer { text-align: center; color: #808080; font-size: 12px; margin-top: 30px; }\n"
       << "    </style>\n"
       << "</head>\n"
       << "<body>\n";
    return ss.str();
}

std::string ReportGenerator::generateHTMLFooter() {
    std::stringstream ss;
    ss << "    <div class=\"footer\">\n"
       << "        <p>Generated by Forensic Data Tool</p>\n"
       << "        <p>" << getCurrentTimestamp() << "</p>\n"
       << "    </div>\n"
       << "</body>\n"
       << "</html>\n";
    return ss.str();
}

std::string ReportGenerator::formatStatusHTML(const std::string& status) {
    if (status == "SUCCESS" || status == "PASSED") {
        return "<span class=\"status-pass\">" + status + "</span>";
    } else if (status == "FAILED") {
        return "<span class=\"status-fail\">" + status + "</span>";
    } else if (status == "INCONCLUSIVE") {
        return "<span class=\"status-inconclusive\">" + status + "</span>";
    }
    return status;
}

std::string ReportGenerator::generateTextReport(
    const AuditRecord& record,
    const std::string& outputPath) {
    
    // Create output directory
    try {
        fs::create_directories(outputPath);
    } catch (const std::exception& e) {
        std::cerr << "[ERROR] Failed to create directory: " << e.what() << std::endl;
        return "";
    }
    
    std::string fileName = outputPath + record.caseID + "_report.txt";
    std::ofstream file(fileName);
    
    if (!file.is_open()) {
        std::cerr << "[ERROR] Failed to open file for writing: " << fileName << std::endl;
        return "";
    }
    
    file << "╔════════════════════════════════════════════════════════════════╗\n";
    file << "║              FORENSIC OPERATION REPORT                         ║\n";
    file << "║                                                                ║\n";
    file << "╚════════════════════════════════════════════════════════════════╝\n\n";
    
    file << "REPORT METADATA\n";
    file << "════════════════════════════════════════════════════════════════\n";
    file << "Generated: " << getCurrentTimestamp() << "\n";
    file << "Case ID:   " << record.caseID << "\n";
    file << "Tool:      Forensic Data Tool v1.0\n\n";
    
    file << "OPERATION SUMMARY\n";
    file << "════════════════════════════════════════════════════════════════\n";
    file << "Operation Type:    " << record.operationType << "\n";
    file << "Status:            " << record.status << "\n";
    file << "Method:            " << record.method << "\n";
    file << "Exit Code:         " << record.exitCode << "\n\n";
    
    file << "DEVICE INFORMATION\n";
    file << "════════════════════════════════════════════════════════════════\n";
    file << "Device Path:       " << record.device << "\n";
    file << "Device Model:      " << record.deviceModel << "\n";
    file << "Device Serial:     " << record.deviceSerial << "\n";
    file << "Device Size:       " << record.deviceSize << "\n\n";
    
    file << "OPERATION TIMELINE\n";
    file << "════════════════════════════════════════════════════════════════\n";
    file << "Start Time:        " << record.startTime << "\n";
    file << "End Time:          " << record.endTime << "\n\n";
    
    if (record.operationType == "RECOVERY") {
        file << "RECOVERY RESULTS\n";
        file << "════════════════════════════════════════════════════════════════\n";
        file << "Files Recovered:   " << record.filesRecovered << "\n\n";
    } else if (record.operationType == "ERASURE") {
        file << "ERASURE RESULTS\n";
        file << "════════════════════════════════════════════════════════════════\n";
        file << "Erasure Method:    " << record.method << "\n";
        file << "Status:            " << (record.status == "SUCCESS" ? "COMPLETE" : "INCOMPLETE") << "\n\n";
    } else if (record.operationType == "VERIFICATION") {
        file << "VERIFICATION RESULTS\n";
        file << "════════════════════════════════════════════════════════════════\n";
        file << "Clearance:         " << std::fixed << std::setprecision(2) << record.erasurePercentage << "%\n";
        file << "Status:            " << record.status << "\n\n";
    }
    
    file << "OPERATION DETAILS\n";
    file << "════════════════════════════════════════════════════════════════\n";
    file << record.details << "\n\n";
    
    file << "INTEGRITY\n";
    file << "════════════════════════════════════════════════════════════════\n";
    file << "Record Hash:       " << record.sha256Hash << "\n\n";
    
    file << "CHAIN OF CUSTODY\n";
    file << "════════════════════════════════════════════════════════════════\n";
    file << "This report represents an official forensic record.\n";
    file << "Any tampering with this document constitutes legal violation.\n\n";
    
    file << "═════════════════════════════════════════════════════════════════\n";
    file << "END OF REPORT\n";
    
    file.close();
    
    std::cout << "[✓] Text report generated: " << fileName << "\n";
    return fileName;
}

std::string ReportGenerator::generateHTMLReport(
    const AuditRecord& record,
    const std::string& outputPath) {
    
    // Create output directory
    try {
        fs::create_directories(outputPath);
    } catch (const std::exception& e) {
        std::cerr << "[ERROR] Failed to create directory: " << e.what() << std::endl;
        return "";
    }
    
    std::string fileName = outputPath + record.caseID + "_report.html";
    std::ofstream file(fileName);
    
    if (!file.is_open()) {
        std::cerr << "[ERROR] Failed to open file for writing: " << fileName << std::endl;
        return "";
    }
    
    file << generateHTMLHeader("Forensic Report - " + record.caseID);
    
    file << "    <div class=\"header\">\n"
         << "        <div class=\"title\">⚠️ FORENSIC OPERATION REPORT</div>\n"
         << "        <div class=\"subtitle\">(Case " << record.caseID << ")</div>\n"
         << "    </div>\n\n";
    
    // Operation Summary
    file << "    <div class=\"section\">\n"
         << "        <div class=\"section-title\">OPERATION SUMMARY</div>\n"
         << "        <div class=\"row\"><div class=\"label\">Operation:</div><div class=\"value\">" << record.operationType << "</div></div>\n"
         << "        <div class=\"row\"><div class=\"label\">Status:</div><div class=\"value\">" << formatStatusHTML(record.status) << "</div></div>\n"
         << "        <div class=\"row\"><div class=\"label\">Method:</div><div class=\"value\">" << record.method << "</div></div>\n"
         << "        <div class=\"row\"><div class=\"label\">Exit Code:</div><div class=\"value\">" << record.exitCode << "</div></div>\n"
         << "    </div>\n\n";
    
    // Device Information
    file << "    <div class=\"section\">\n"
         << "        <div class=\"section-title\">DEVICE INFORMATION</div>\n"
         << "        <div class=\"row\"><div class=\"label\">Device:</div><div class=\"value\">" << record.device << "</div></div>\n"
         << "        <div class=\"row\"><div class=\"label\">Model:</div><div class=\"value\">" << record.deviceModel << "</div></div>\n"
         << "        <div class=\"row\"><div class=\"label\">Serial:</div><div class=\"value\">" << record.deviceSerial << "</div></div>\n"
         << "        <div class=\"row\"><div class=\"label\">Size:</div><div class=\"value\">" << record.deviceSize << "</div></div>\n"
         << "    </div>\n\n";
    
    // Timeline
    file << "    <div class=\"section\">\n"
         << "        <div class=\"section-title\">OPERATION TIMELINE</div>\n"
         << "        <div class=\"row\"><div class=\"label\">Start:</div><div class=\"value\">" << record.startTime << "</div></div>\n"
         << "        <div class=\"row\"><div class=\"label\">End:</div><div class=\"value\">" << record.endTime << "</div></div>\n"
         << "    </div>\n\n";
    
    // Operation-specific results
    if (record.operationType == "RECOVERY") {
        file << "    <div class=\"section\">\n"
             << "        <div class=\"section-title\">RECOVERY RESULTS</div>\n"
             << "        <div class=\"row\"><div class=\"label\">Files Recovered:</div><div class=\"value\">" << record.filesRecovered << "</div></div>\n"
             << "    </div>\n\n";
    } else if (record.operationType == "ERASURE") {
        file << "    <div class=\"section\">\n"
             << "        <div class=\"section-title\">ERASURE RESULTS</div>\n"
             << "        <div class=\"row\"><div class=\"label\">Erasure Method:</div><div class=\"value\">" << record.method << "</div></div>\n"
             << "        <div class=\"row\"><div class=\"label\">Completion:</div><div class=\"value\">" << (record.status == "SUCCESS" ? "COMPLETE" : "INCOMPLETE") << "</div></div>\n"
             << "    </div>\n\n";
    } else if (record.operationType == "VERIFICATION") {
        file << "    <div class=\"section\">\n"
             << "        <div class=\"section-title\">VERIFICATION RESULTS</div>\n"
             << "        <div class=\"row\"><div class=\"label\">Clearance:</div><div class=\"value\">" 
             << std::fixed << std::setprecision(2) << record.erasurePercentage << "%</div></div>\n"
             << "        <div class=\"row\"><div class=\"label\">Status:</div><div class=\"value\">" << formatStatusHTML(record.status) << "</div></div>\n"
             << "    </div>\n\n";
    }
    
    // Details
    file << "    <div class=\"section\">\n"
         << "        <div class=\"section-title\">OPERATION DETAILS</div>\n"
         << "        <pre>" << record.details << "</pre>\n"
         << "    </div>\n\n";
    
    // Integrity
    file << "    <div class=\"section\">\n"
         << "        <div class=\"section-title\">INTEGRITY & CHAIN OF CUSTODY</div>\n"
         << "        <div class=\"row\"><div class=\"label\">Record Hash:</div><div class=\"value\">" << record.sha256Hash << "</div></div>\n"
         << "        <p style=\"color: #ffff00;\">This record represents an official forensic document.\n"
         << "        Any tampering with this document constitutes a legal violation.</p>\n"
         << "    </div>\n\n";
    
    file << generateHTMLFooter();
    
    file.close();
    
    std::cout << "[✓] HTML report generated: " << fileName << "\n";
    return fileName;
}

std::string ReportGenerator::generateAuditSummary(
    const std::vector<std::string>& caseIDs,
    const std::string& outputPath) {
    
    // Create output directory
    try {
        fs::create_directories(outputPath);
    } catch (const std::exception& e) {
        std::cerr << "[ERROR] Failed to create directory: " << e.what() << std::endl;
        return "";
    }
    
    std::string fileName = outputPath + "audit_summary.txt";
    std::ofstream file(fileName);
    
    if (!file.is_open()) {
        std::cerr << "[ERROR] Failed to open file for writing: " << fileName << std::endl;
        return "";
    }
    
    file << "╔════════════════════════════════════════════════════════════════╗\n";
    file << "║              FORENSIC AUDIT SUMMARY                            ║\n";
    file << "╚════════════════════════════════════════════════════════════════╝\n\n";
    
    file << "Generated: " << getCurrentTimestamp() << "\n";
    file << "Total Cases: " << caseIDs.size() << "\n\n";
    
    file << "CASE INDEX\n";
    file << "════════════════════════════════════════════════════════════════\n";
    
    for (size_t i = 0; i < caseIDs.size(); ++i) {
        file << (i + 1) << ". " << caseIDs[i] << "\n";
    }
    
    file << "\n════════════════════════════════════════════════════════════════\n";
    file << "END OF SUMMARY\n";
    
    file.close();
    
    std::cout << "[✓] Audit summary generated: " << fileName << "\n";
    return fileName;
}

std::string ReportGenerator::generateChainOfCustodyReport(
    const std::string& caseID,
    const std::string& outputPath) {
    
    // Create output directory
    try {
        fs::create_directories(outputPath);
    } catch (const std::exception& e) {
        std::cerr << "[ERROR] Failed to create directory: " << e.what() << std::endl;
        return "";
    }
    
    std::string fileName = outputPath + caseID + "_coc.txt";
    std::ofstream file(fileName);
    
    if (!file.is_open()) {
        std::cerr << "[ERROR] Failed to open file for writing: " << fileName << std::endl;
        return "";
    }
    
    file << "╔════════════════════════════════════════════════════════════════╗\n";
    file << "║         CHAIN OF CUSTODY DOCUMENTATION                         ║\n";
    file << "║                                                                ║\n";
    file << "╚════════════════════════════════════════════════════════════════╝\n\n";
    
    file << "Case ID: " << caseID << "\n";
    file << "Generated: " << getCurrentTimestamp() << "\n\n";
    
    file << "CUSTODIAL RESPONSIBILITY\n";
    file << "════════════════════════════════════════════════════════════════\n";
    file << "This document certifies the chain of custody for the above case.\n\n";
    
    file << "Initial Handler:       Forensic Data Tool\n";
    file << "Date/Time Received:    " << getCurrentTimestamp() << "\n";
    file << "Purpose:               Forensic Analysis\n\n";
    
    file << "CUSTODY TRANSFERS\n";
    file << "════════════════════════════════════════════════════════════════\n";
    file << "[No transfers recorded]\n\n";
    
    file << "DEVICE HANDLING\n";
    file << "════════════════════════════════════════════════════════════════\n";
    file << "All devices were handled in accordance with forensic standards.\n";
    file << "Write protections were implemented where applicable.\n";
    file << "Chain of custody was maintained throughout the process.\n\n";
    
    file << "SIGNATURES\n";
    file << "════════════════════════════════════════════════════════════════\n";
    file << "Analyst Name: _______________________  Date: __________\n";
    file << "Signature:    _______________________\n\n";
    
    file << "Supervisor:   _______________________  Date: __________\n";
    file << "Signature:    _______________________\n\n";
    
    file << "════════════════════════════════════════════════════════════════\n";
    file << "END OF CHAIN OF CUSTODY DOCUMENTATION\n";
    
    file.close();
    
    std::cout << "[✓] Chain of custody report generated: " << fileName << "\n";
    return fileName;
}
